/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BlascoMatiasMartin_tp6;

/**
 *
 * @author M
 */
public class VistaBorrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaBorrarCliente
     */
    public VistaBorrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        borrarDNI = new javax.swing.JLabel();
        borrarTelefono = new javax.swing.JLabel();
        borrarApellido = new javax.swing.JLabel();
        borrarNombre = new javax.swing.JLabel();
        borrarCiudad = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        borrarSalir = new javax.swing.JButton();
        borrarBuscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Borrar Clientes");

        borrarDNI.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        borrarDNI.setForeground(new java.awt.Color(51, 204, 255));
        borrarDNI.setText("DNI:");

        borrarTelefono.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        borrarTelefono.setForeground(new java.awt.Color(51, 204, 255));
        borrarTelefono.setText("TELEFONO:");

        borrarApellido.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        borrarApellido.setForeground(new java.awt.Color(51, 204, 255));
        borrarApellido.setText("APELLIDO:");

        borrarNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        borrarNombre.setForeground(new java.awt.Color(51, 204, 255));
        borrarNombre.setText("NOMBRE:");

        borrarCiudad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        borrarCiudad.setForeground(new java.awt.Color(51, 204, 255));
        borrarCiudad.setText("CIUDAD:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        borrarSalir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        borrarSalir.setText("SALIR");
        borrarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarSalirActionPerformed(evt);
            }
        });

        borrarBuscar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        borrarBuscar.setText("BUSCAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrarDNI)
                    .addComponent(borrarTelefono)
                    .addComponent(borrarApellido)
                    .addComponent(borrarNombre)
                    .addComponent(borrarCiudad))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borrarBuscar)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrarSalir)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarDNI)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarTelefono)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarApellido)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarNombre)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarCiudad)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(borrarSalir)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrarApellido;
    private javax.swing.JButton borrarBuscar;
    private javax.swing.JLabel borrarCiudad;
    private javax.swing.JLabel borrarDNI;
    private javax.swing.JLabel borrarNombre;
    private javax.swing.JButton borrarSalir;
    private javax.swing.JLabel borrarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
