/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BlascoMatiasMartin_tp6;

import javax.swing.JOptionPane;

/**
 *
 * @author M
 */
public class VistaAgregarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAgregarCliente
     */
    public VistaAgregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agregarDNI = new javax.swing.JLabel();
        agregarApellid = new javax.swing.JLabel();
        agregarNombre = new javax.swing.JLabel();
        agregarCiudad = new javax.swing.JLabel();
        agregarDom = new javax.swing.JLabel();
        agregarTelefono = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCiudad = new javax.swing.JTextField();
        jtDomicilio = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        agregarNuevo = new javax.swing.JButton();
        agregarGuardar = new javax.swing.JButton();
        agregarSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Agregar Clientes");

        agregarDNI.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        agregarDNI.setForeground(new java.awt.Color(51, 204, 255));
        agregarDNI.setText("DNI:");

        agregarApellid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        agregarApellid.setForeground(new java.awt.Color(51, 204, 255));
        agregarApellid.setText("APELLIDO:");

        agregarNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        agregarNombre.setForeground(new java.awt.Color(51, 204, 255));
        agregarNombre.setText("NOMBRE");

        agregarCiudad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        agregarCiudad.setForeground(new java.awt.Color(51, 204, 255));
        agregarCiudad.setText("CIUDAD:");

        agregarDom.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        agregarDom.setForeground(new java.awt.Color(51, 204, 255));
        agregarDom.setText("DOMICILIO:");

        agregarTelefono.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        agregarTelefono.setForeground(new java.awt.Color(51, 204, 255));
        agregarTelefono.setText("TELEFONO:");

        agregarNuevo.setText("Nuevo");
        agregarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNuevoActionPerformed(evt);
            }
        });

        agregarGuardar.setText("Guardar");
        agregarGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarGuardarActionPerformed(evt);
            }
        });

        agregarSalir.setText("Salir");
        agregarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(agregarApellid)
                                        .addComponent(agregarDNI)
                                        .addComponent(agregarNombre)
                                        .addComponent(agregarCiudad))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agregarDom)
                                    .addComponent(agregarTelefono))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(agregarNuevo)
                        .addGap(44, 44, 44)
                        .addComponent(agregarGuardar)
                        .addGap(39, 39, 39)
                        .addComponent(agregarSalir)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarDNI)
                            .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarApellid)
                            .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarNombre)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarCiudad)
                            .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarDom, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarTelefono)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarNuevo)
                            .addComponent(agregarGuardar)
                            .addComponent(agregarSalir))
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarGuardarActionPerformed
        int dni = Integer.parseInt(jtDni.getText());
        String nombre = jtNombre.getText();
        String apellido = jtApellido.getText();
        String ciudad = jtCiudad.getText();
        String domicilio = jtDomicilio.getText();
        long telefono = Long.parseLong(jtTelefono.getText());
        
        Cliente c1 = new Cliente (dni, nombre, apellido, ciudad, domicilio);
        
        boolean seAgrego = Directorio.agregarCliente(telefono, c1);
            if(!seAgrego){
                Menu menu = new Menu();
                JOptionPane.showMessageDialog(menu, "El numero que desea agregar ya esta asociado a otro cliente");
            }else{
                Menu menu = new Menu();
                JOptionPane.showMessageDialog(menu, "Se agrego correctamente");
            }
    }//GEN-LAST:event_agregarGuardarActionPerformed

    private void agregarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSalirActionPerformed
        dispose();
    }//GEN-LAST:event_agregarSalirActionPerformed

    private void agregarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNuevoActionPerformed
        jtDni.setText("");
        jtNombre.setText("");
        jtApellido.setText("");
        jtCiudad.setText("");
        jtDomicilio.setText("");
        jtTelefono.setText("");
    }//GEN-LAST:event_agregarNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarApellid;
    private javax.swing.JLabel agregarCiudad;
    private javax.swing.JLabel agregarDNI;
    private javax.swing.JLabel agregarDom;
    private javax.swing.JButton agregarGuardar;
    private javax.swing.JLabel agregarNombre;
    private javax.swing.JButton agregarNuevo;
    private javax.swing.JButton agregarSalir;
    private javax.swing.JLabel agregarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtDomicilio;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
