/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BlascoMatiasMartin_tp6;
import javax.swing.JOptionPane;
/**
 *
 * @author M
 */
public class VistaBusquedaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaBusquedaCliente
     */
    public VistaBusquedaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarTelefono = new javax.swing.JLabel();
        buscarDNI = new javax.swing.JLabel();
        buscarApellido = new javax.swing.JLabel();
        buscarNombre = new javax.swing.JLabel();
        buscarCiudad = new javax.swing.JLabel();
        buscarSalir = new javax.swing.JButton();
        jtTelefono = new javax.swing.JTextField();
        jtDni = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCiudad = new javax.swing.JTextField();
        buscarBuscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Busqueda de Clientes");

        buscarTelefono.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        buscarTelefono.setForeground(new java.awt.Color(51, 204, 255));
        buscarTelefono.setText("TELEFONO:");

        buscarDNI.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        buscarDNI.setForeground(new java.awt.Color(51, 204, 255));
        buscarDNI.setText("DNI:");

        buscarApellido.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        buscarApellido.setForeground(new java.awt.Color(51, 204, 255));
        buscarApellido.setText("APELLIDO:");

        buscarNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        buscarNombre.setForeground(new java.awt.Color(51, 204, 255));
        buscarNombre.setText("NOMBRE:");

        buscarCiudad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        buscarCiudad.setForeground(new java.awt.Color(51, 204, 255));
        buscarCiudad.setText("CIUDAD:");

        buscarSalir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buscarSalir.setText("SALIR");
        buscarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSalirActionPerformed(evt);
            }
        });

        jtTelefono.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jtDni.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jtApellido.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jtNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jtCiudad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        buscarBuscar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buscarBuscar.setText("Buscar");
        buscarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buscarNombre)
                                    .addComponent(buscarDNI)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buscarTelefono)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(buscarBuscar))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(buscarApellido)
                                                .addGap(25, 25, 25))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buscarCiudad)
                                                .addGap(37, 37, 37)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(jtNombre)
                                            .addComponent(jtCiudad)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarTelefono)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBuscar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarDNI)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarApellido)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarNombre)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarCiudad)
                    .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(buscarSalir)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSalirActionPerformed
        dispose();
    }//GEN-LAST:event_buscarSalirActionPerformed

    private void buscarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBuscarActionPerformed
        Long telefono = Long.parseLong(jtTelefono.getText());
        Cliente cliente = Directorio.buscarCliente(telefono);
        
        if(cliente == null){
            Menu menu = new Menu();
            JOptionPane.showMessageDialog(menu, "El cliente no existe");
        }else{
            jtDni.setText(String.valueOf(cliente.getDni()));
            jtNombre.setText(cliente.getNombre());
            jtApellido.setText(cliente.getApellido());
            jtCiudad.setText(cliente.getCiudad());
            
        }
    }//GEN-LAST:event_buscarBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarApellido;
    private javax.swing.JButton buscarBuscar;
    private javax.swing.JLabel buscarCiudad;
    private javax.swing.JLabel buscarDNI;
    private javax.swing.JLabel buscarNombre;
    private javax.swing.JButton buscarSalir;
    private javax.swing.JLabel buscarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
